/*
 * listFix() - Fix Broken Playlists!
 *
 * This file is part of listFix().
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, please see http://www.gnu.org/licenses/
 */

package listfix.view.dialogs;

import java.awt.Dimension;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.beans.PropertyChangeSupport;
import javax.swing.JLabel;
import javax.swing.JProgressBar;
import javax.swing.SwingWorker;

public class ProgressDialog extends javax.swing.JDialog
{
    public ProgressDialog(java.awt.Frame parent, boolean modal, SwingWorker worker, String label)
    {
        super(parent, modal);
        initComponents();

        Dimension sz = getSize();
        sz.width = 400;
        setSize(sz);
        setLocationRelativeTo(parent);

        initWorker(worker);

        jLabel1.setText(label);

        addWindowListener(new WindowAdapter()
        {
            @Override
            public void windowOpened(WindowEvent e)
            {
                _worker.execute();
            }
        });

    }

    public JProgressBar getProgressBar()
    {
        return jProgressBar1;
    }

    public JLabel getProgressLabel()
    {
        return jLabel1;
    }
    
    private void initWorker(SwingWorker worker)
    {
        _worker = worker;
        PropertyChangeSupport pcs = _worker.getPropertyChangeSupport();
        
        // update progress bar when progress changes
        pcs.addPropertyChangeListener("progress", new PropertyChangeListener() 
        {
            public void propertyChange(PropertyChangeEvent evt)
            {
                int progress = (Integer)evt.getNewValue();
                jProgressBar1.setValue(progress);
            }
        });
        
        // close dialog when state changes to done
        pcs.addPropertyChangeListener("state", new PropertyChangeListener() 
        {
            public void propertyChange(PropertyChangeEvent evt)
            {
                if (_worker.isDone())
                {
                    setVisible(false);
                }
            }
        });
        
    }

    SwingWorker _worker;

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 9));
        jLabel1.setText("jLabel1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 4, 10);
        getContentPane().add(jLabel1, gridBagConstraints);

        jProgressBar1.setMinimumSize(new java.awt.Dimension(250, 14));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
        getContentPane().add(jProgressBar1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables

}
