

package listfix.view.dialogs;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JPanel;
import javax.swing.WindowConstants;
import javax.swing.table.TableCellEditor;
import listfix.model.BatchMatchItem;
import listfix.view.controls.ClosestMatchesSearchScrollableResultsPanel;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

/**
 * This is the results dialog we display when running a closest matches search on multiple files in a playlist (this operation originally worked only on a single entry)..
 * @author jcaron
 */
public class BatchClosestMatchResultsDialog extends JDialog
{
  

  /**
   *
   * 
   * 
   */
  public BatchClosestMatchResultsDialog(Frame parent, List<BatchMatchItem> items)
  {
    super(parent, true);
    _items = items;
    initComponents();

    // get screenwidth using workaround for vmware/linux bug
        int screenWidth;
        DisplayMode dmode = getGraphicsConfiguration().getDevice().getDisplayMode();
        if (dmode != null)
    {
            screenWidth = dmode.getWidth();
    }
        else
    {
            screenWidth = getGraphicsConfiguration().getBounds().width;
    }
        int newWidth = _pnlResults.getTableWidth() + getWidth() - _pnlResults.getWidth() + 2;
        setSize(Math.min(newWidth, screenWidth - 50), getHeight());
  }

  /**
   *
   * 
   */
  public boolean isAccepted()
  {
    return _isAccepted;
  }
  private boolean _isAccepted;

  public List<BatchMatchItem> getMatches()
  {
    return _items;
  }
  private List<BatchMatchItem> _items;

  /**
   * This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new JPanel();
        _btnOk = new JButton();
        _btnCancel = new JButton();
        _pnlResults = new ClosestMatchesSearchScrollableResultsPanel(_items);

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Select Closest Matches");

        jPanel1.setLayout(new FlowLayout(FlowLayout.RIGHT));

        _btnOk.setText("OK");
        _btnOk.addActionListener(new ActionListener() {
            @Override public void actionPerformed(ActionEvent evt) {
                onBtnOkActionPerformed();
            }
        });
        jPanel1.add(_btnOk);

        _btnCancel.setText("Cancel");
        _btnCancel.addActionListener(new ActionListener() {
            @Override public void actionPerformed(ActionEvent evt) {
                onBtnCancelActionPerformed();
            }
        });
        jPanel1.add(_btnCancel);

        getContentPane().add(jPanel1, BorderLayout.SOUTH);
        getContentPane().add(_pnlResults, BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onBtnOkActionPerformed()//GEN-FIRST:event_onBtnOkActionPerformed
    {//GEN-HEADEREND:event_onBtnOkActionPerformed
    _isAccepted = true;
    if (_pnlResults.getSelectedRow() > -1 && _pnlResults.getSelectedColumn() == 3)
    {
      TableCellEditor cellEditor = _pnlResults.getCellEditor(_pnlResults.getSelectedRow(), _pnlResults.getSelectedColumn());
      cellEditor.stopCellEditing();
    }
    setVisible(false);
    }//GEN-LAST:event_onBtnOkActionPerformed

    private void onBtnCancelActionPerformed()//GEN-FIRST:event_onBtnCancelActionPerformed
    {//GEN-HEADEREND:event_onBtnCancelActionPerformed
    _isAccepted = false;
    setVisible(false);
    }//GEN-LAST:event_onBtnCancelActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton _btnCancel;
    private JButton _btnOk;
    private ClosestMatchesSearchScrollableResultsPanel _pnlResults;
    private JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
