package listfix.view.dialogs;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.*;
import listfix.model.EditFilenameResult;

public class EditFilenameDialog extends JDialog {
  private static final long serialVersionUID = 1825443635993970657L;

  public static final int OK = 0;

  public static final int CANCEL = 1;
  private int resultCode = CANCEL;
  private String fileName;

  /** Creates new form EditFilenameDialog */
  public EditFilenameDialog(Frame parent, String title, boolean modal, String fileName) {
    super(parent, title, modal);
    initComponents();
    txtFilename.setText(fileName);
    this.getRootPane().setDefaultButton(btnOk);
    this.center();
  }

  public EditFilenameDialog() {}

  public String getFileName() {
    return fileName;
  }

  public void setFileName(String x) {
    fileName = x;
  }

  public void setResultCode(int i) {
    resultCode = i;
  }

  public int getResultCode() {
    return resultCode;
  }

  private void center() {
    Point parentLocation = this.getParent().getLocationOnScreen();
    double x = parentLocation.getX();
    double y = parentLocation.getY();
    int width = this.getParent().getWidth();
    int height = this.getParent().getHeight();

    this.setLocation(
        (int) x + (width - this.getWidth()) / 2, (int) y + (height - this.getHeight()) / 2);
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    GridBagConstraints gridBagConstraints;

    jPanel1 = new JPanel();
    jLabel2 = new JLabel();
    jLabel3 = new JLabel();
    jLabel4 = new JLabel();
    jPanel2 = new JPanel();
    jLabel1 = new JLabel();
    txtFilename = new JTextField();
    jPanel3 = new JPanel();
    btnOk = new JButton();
    btnCancel = new JButton();

    addWindowListener(
        new WindowAdapter() {
          @Override
          public void windowClosing(WindowEvent evt) {
            closeDialog();
          }
        });
    getContentPane().setLayout(new BoxLayout(getContentPane(), BoxLayout.Y_AXIS));

    jPanel1.setLayout(new GridBagLayout());

    jLabel2.setText("If you renamed a file by hand");
    gridBagConstraints = new GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.insets = new Insets(10, 0, 0, 0);
    jPanel1.add(jLabel2, gridBagConstraints);

    jLabel3.setText("and know the new filename, ");
    gridBagConstraints = new GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    jPanel1.add(jLabel3, gridBagConstraints);

    jLabel4.setText("you can enter it below.");
    gridBagConstraints = new GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    jPanel1.add(jLabel4, gridBagConstraints);

    getContentPane().add(jPanel1);

    jPanel2.setMaximumSize(null);

    jLabel1.setText("New Filename:");
    jPanel2.add(jLabel1);

    txtFilename.setMinimumSize(new Dimension(150, 20));
    txtFilename.setPreferredSize(new Dimension(250, 20));
    jPanel2.add(txtFilename);

    getContentPane().add(jPanel2);

    jPanel3.setMaximumSize(null);

    btnOk.setText("OK");
    btnOk.addActionListener(
        new ActionListener() {
          @Override
          public void actionPerformed(ActionEvent evt) {
            btnOkActionPerformed();
          }
        });
    jPanel3.add(btnOk);

    btnCancel.setText("Cancel");
    btnCancel.addActionListener(
        new ActionListener() {
          @Override
          public void actionPerformed(ActionEvent evt) {
            btnCancelActionPerformed();
          }
        });
    jPanel3.add(btnCancel);

    getContentPane().add(jPanel3);

    pack();
  } // </editor-fold>//GEN-END:initComponents

  private void btnCancelActionPerformed() { // GEN-FIRST:event_btnCancelActionPerformed
    setVisible(false);
    dispose();
    setResultCode(CANCEL);
  } // GEN-LAST:event_btnCancelActionPerformed

  private void btnOkActionPerformed() { // GEN-FIRST:event_btnOkActionPerformed
    setVisible(false);
    setFileName(txtFilename.getText());
    dispose();
    setResultCode(OK);
  } // GEN-LAST:event_btnOkActionPerformed

  /** Closes the dialog */
  private void closeDialog() { // GEN-FIRST:event_closeDialog
    setVisible(false);
    dispose();
  } // GEN-LAST:event_closeDialog

  public static EditFilenameResult showDialog(
      Frame parent, String title, boolean modal, String fileName) {
    EditFilenameDialog tempDBox = new EditFilenameDialog(parent, title, modal, fileName);
    tempDBox.setVisible(true);
    return new EditFilenameResult(tempDBox.getResultCode(), tempDBox.getFileName());
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private JButton btnCancel;
  private JButton btnOk;
  private JLabel jLabel1;
  private JLabel jLabel2;
  private JLabel jLabel3;
  private JLabel jLabel4;
  private JPanel jPanel1;
  private JPanel jPanel2;
  private JPanel jPanel3;
  private JTextField txtFilename;
  // End of variables declaration//GEN-END:variables
}
