package listfix.view.dialogs;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.*;
import listfix.model.playlists.Playlist;

public class ReorderPlaylistDialog extends JDialog {

  /** Creates new form ReorderPlaylistDialog */
  public ReorderPlaylistDialog(
      Frame parent, boolean modal, Playlist.SortIx sortIx, boolean isDescending) {
    super(parent, modal);
    initComponents();

    switch (sortIx) {
      case None:
        _rbReverse.setSelected(true);
        break;

      case Filename:
        _rbFilename.doClick();
        _chkDescending.setSelected(isDescending);
        break;

      case Path:
        _rbPath.doClick();
        _chkDescending.setSelected(isDescending);
        break;

      case Status:
        _rbStatus.doClick();
        _chkDescending.setSelected(isDescending);
        break;

      default:
        _rbRandom.setSelected(true);
    }
  }

  public Playlist.SortIx getSelectedSortIx() {
    if (_wasCancelled) return Playlist.SortIx.None;
    else if (_rbRandom.isSelected()) return Playlist.SortIx.Random;
    else if (_rbReverse.isSelected()) return Playlist.SortIx.Reverse;
    else if (_rbFilename.isSelected()) return Playlist.SortIx.Filename;
    else if (_rbPath.isSelected()) return Playlist.SortIx.Path;
    else if (_rbStatus.isSelected()) return Playlist.SortIx.Status;
    else return Playlist.SortIx.None;
  }

  boolean _wasCancelled;

  public boolean getIsDescending() {
    return _chkDescending.isSelected();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    buttonGroup1 = new ButtonGroup();
    jPanel1 = new JPanel();
    _rbRandom = new JRadioButton();
    _rbReverse = new JRadioButton();
    _rbFilename = new JRadioButton();
    _rbPath = new JRadioButton();
    _rbStatus = new JRadioButton();
    _chkDescending = new JCheckBox();
    jPanel2 = new JPanel();
    jButton1 = new JButton();
    jButton2 = new JButton();

    setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Reorder Playlist");
    setMinimumSize(new Dimension(300, 189));
    setModal(true);
    setResizable(false);

    jPanel1.setBorder(BorderFactory.createTitledBorder("Select the new playlist order"));
    jPanel1.setAlignmentX(1.0F);
    jPanel1.setLayout(new GridLayout(6, 1));

    buttonGroup1.add(_rbRandom);
    _rbRandom.setText("Randomized");
    _rbRandom.addActionListener(
        new ActionListener() {
          @Override
          public void actionPerformed(ActionEvent evt) {
            onUnsortedOptionSelected();
          }
        });
    jPanel1.add(_rbRandom);

    buttonGroup1.add(_rbReverse);
    _rbReverse.setText("Reversed");
    _rbReverse.addActionListener(
        new ActionListener() {
          @Override
          public void actionPerformed(ActionEvent evt) {
            onUnsortedOptionSelected();
          }
        });
    jPanel1.add(_rbReverse);

    buttonGroup1.add(_rbFilename);
    _rbFilename.setText("By Filename");
    _rbFilename.addActionListener(
        new ActionListener() {
          @Override
          public void actionPerformed(ActionEvent evt) {
            onSortedOptionSelected();
          }
        });
    jPanel1.add(_rbFilename);

    buttonGroup1.add(_rbPath);
    _rbPath.setText("By Location");
    _rbPath.addActionListener(
        new ActionListener() {
          @Override
          public void actionPerformed(ActionEvent evt) {
            onSortedOptionSelected();
          }
        });
    jPanel1.add(_rbPath);

    buttonGroup1.add(_rbStatus);
    _rbStatus.setText("By Status");
    _rbStatus.addActionListener(
        new ActionListener() {
          @Override
          public void actionPerformed(ActionEvent evt) {
            onSortedOptionSelected();
          }
        });
    jPanel1.add(_rbStatus);

    _chkDescending.setText("Descending");
    _chkDescending.setEnabled(false);
    jPanel1.add(_chkDescending);

    getContentPane().add(jPanel1, BorderLayout.CENTER);

    jPanel2.setLayout(new FlowLayout(FlowLayout.RIGHT));

    jButton1.setText("Proceed");
    jButton1.addActionListener(
        new ActionListener() {
          @Override
          public void actionPerformed(ActionEvent evt) {
            onBtnOkActionPerformed();
          }
        });
    jPanel2.add(jButton1);

    jButton2.setText("Cancel");
    jButton2.addActionListener(
        new ActionListener() {
          @Override
          public void actionPerformed(ActionEvent evt) {
            onBtnCancelActionPerformed();
          }
        });
    jPanel2.add(jButton2);

    getContentPane().add(jPanel2, BorderLayout.SOUTH);

    pack();
  } // </editor-fold>//GEN-END:initComponents

  private void onBtnCancelActionPerformed() // GEN-FIRST:event_onBtnCancelActionPerformed
      { // GEN-HEADEREND:event_onBtnCancelActionPerformed
    _wasCancelled = true;
    setVisible(false);
  } // GEN-LAST:event_onBtnCancelActionPerformed

  private void onBtnOkActionPerformed() // GEN-FIRST:event_onBtnOkActionPerformed
      { // GEN-HEADEREND:event_onBtnOkActionPerformed
    setVisible(false);
  } // GEN-LAST:event_onBtnOkActionPerformed

  private void onUnsortedOptionSelected() // GEN-FIRST:event_onUnsortedOptionSelected
      { // GEN-HEADEREND:event_onUnsortedOptionSelected
    _chkDescending.setEnabled(false);
  } // GEN-LAST:event_onUnsortedOptionSelected

  private void onSortedOptionSelected() // GEN-FIRST:event_onSortedOptionSelected
      { // GEN-HEADEREND:event_onSortedOptionSelected
    _chkDescending.setEnabled(true);
  } // GEN-LAST:event_onSortedOptionSelected

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private JCheckBox _chkDescending;
  private JRadioButton _rbFilename;
  private JRadioButton _rbPath;
  private JRadioButton _rbRandom;
  private JRadioButton _rbReverse;
  private JRadioButton _rbStatus;
  private ButtonGroup buttonGroup1;
  private JButton jButton1;
  private JButton jButton2;
  private JPanel jPanel1;
  private JPanel jPanel2;
  // End of variables declaration//GEN-END:variables
}
