package listfix.view;


import listfix.io.M3UFilter;

/*
 * LoadM3UDialog.java
 *
 * Created on October 24, 2001, 1:55 AM
 */

/**
 *
 * @author  Administrator
 */
public class LoadM3UDialog extends javax.swing.JFrame {

    /** Creates new form LoadM3UDialog */
    public LoadM3UDialog() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jPanel1 = new javax.swing.JPanel();
        jFileChooser1 = new javax.swing.JFileChooser();
        
        setTitle("Choose a Playlist...");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 300));
        jFileChooser1.setDialogTitle("Choose a Playlist...");
        jFileChooser1.setCurrentDirectory(new java.io.File("C:\\"));
        jFileChooser1.setAcceptAllFileFilterUsed(false);
        jFileChooser1.setFileFilter(new M3UFilter());
        jFileChooser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooser1ActionPerformed(evt);
            }
        });
        
        jPanel1.add(jFileChooser1);
        
        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);
        
        pack();
    }//GEN-END:initComponents

    private void jFileChooser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooser1ActionPerformed
        // Add your handling code here:
    }//GEN-LAST:event_jFileChooser1ActionPerformed

    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        this.setVisible(false);
    }//GEN-LAST:event_exitForm

    private void approveSelection()
    {
        
    }
    
    private void cancelSelection()
    {
        this.setVisible(false);
    }
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        new LoadM3UDialog().setVisible(true);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JFileChooser jFileChooser1;
    // End of variables declaration//GEN-END:variables

}
