name: CI

on:
  workflow_call

jobs:
  ubuntuBuild:
    name: Build deployment on Ubuntu
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for all tags and branches
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: corretto
          cache: gradle
      - name: Git describe
        id: ghd
        uses: proudust/gh-describe@v1
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build
        run: ./gradlew :build
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Gradle Tests
          path: build/test-results/test/*.xml
          reporter: java-junit
          fail-on-error: true
      - name: Build fatJar
        run: ./gradlew :fatJar
      - name: Upload fatJar artifact
        uses: actions/upload-artifact@v3
        with:
          name: fatJar-${{ steps.ghd.outputs.describe }}
          path: build/libs/listFix-*-all.jar
  windowsBuild:
    name: Build deployment on Windows
    runs-on: windows-latest
    permissions:
      checks: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for all tags and branches
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: corretto
          cache: gradle
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Git describe
        id: ghd
        uses: proudust/gh-describe@v1
      - name: Build
        run: ./gradlew :build
      - name: Build Windows installers
        run: ./gradlew :jpackage
      - name: Upload Windows exe installer
        uses: actions/upload-artifact@v3
        with:
          name: listFix-windows-installer-exe-${{ steps.ghd.outputs.describe }}
          path: build/jpackage/listFix()-*.exe
      - name: Upload Windows binaries
        uses: actions/upload-artifact@v3
        with:
          name: listFix-windows-binaries-${{ steps.ghd.outputs.describe }}
          path: build/jpackage/listFix()
