name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for all tags and branches
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: corretto
          cache: gradle
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build
        run: ./gradlew :build
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Gradle Tests
          path: build/test-results/test/*.xml
          reporter: java-junit
          fail-on-error: true
      - name: Build fatJar
        run: ./gradlew :fatJar
      - name: Upload fatJar artifact
        uses: actions/upload-artifact@v3
        with:
          name: fatJar
          path: build/libs/listFix-*-all.jar
