name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for all tags and branches
      - name: Set up JDK 15
        uses: actions/setup-java@v2
        with:
          java-version: 15
          distribution: 'adopt'
          cache: 'gradle'
      - name: Build (Gradle)
        run: ./gradlew build
      - name: Run unit tests (Gradle)
        run: ./gradlew test
      - name: CheckStyle (Gradle)
        run: ./gradlew check