name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for all tags and branches
      - name: Set up JDK 15
        uses: actions/setup-java@v2
        with:
          java-version: 15
          distribution: 'adopt'
          cache: 'gradle'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build
        run: ./gradlew :build
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Gradle Tests
          path: build/test-results/test/*.xml
          reporter: java-junit
          fail-on-error: true