name: Pull Request

on:
  pull_request:
    types: [synchronize]

jobs:
  build:
    uses: Borewit/listFix/.github/workflows/ci.yml@improve-ci
  commentArtifacts:
    name: Link build artifacts
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      pull-requests: write
    steps:
      - name: Comment PR linking artifact
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            [Build run (#${{ github.run_id }}, attempt #${{ github.run_attempt }}) artifacts](https://github.com/Borewit/listFix/actions/runs/${{ github.run_id }}/attempts/${{ github.run_attempt }}#artifacts)
